from collections import namedtuple
import math
import pandas as pd
import streamlit as st
from geopy import geocoders
from geopy.exc import GeocoderTimedOut
from geopy.geocoders import Nominatim
from scipy.spatial import distance
import folium
from streamlit_folium import folium_static


# Function for get geo coordinates from address
def get_location_by_address(address):
    try:
        # Create geocoder object
        # g = geocoders.GoogleV3() #api_key='Asefsefsefdsefsefsefs')
        app = Nominatim(user_agent="tutorial")
        #location = g.geocode(address, timeout=10)
        location = app.geocode(address, timeout=1000)
        latitude = location.latitude
        longitude = location.longitude
        return (float(latitude),float(longitude), location.address)
    except AttributeError:
        print("Problem with data or cannot Geocode.")
    except GeocoderTimedOut:
        print('GeocoderTimedOut')

# function to filter dataframe by distance from point (lat, lon) 
# using distance.euclidean function and return N nearest points
# filtered by object_type column before calculating distance

def get_nearest_points(df, lat, lon, N, object_type):
    # filter dataframe by object_type
    df2 = df[df['object_type'] == object_type]
    
    # calculate distance from point (lat, lon) to each point in dataframe
    df2.loc[:, 'distance'] = df2.apply(lambda row: distance.euclidean((lat, lon), (row['latitude'], row['longitude'])), axis=1)

    # sort dataframe by distance column in ascending order
    df2 = df2.sort_values(by=['distance'])
    # return N nearest points
    return df2.head(N)

st.header("Calculate your property price")

col1, col2 = st.columns([1, 2])

# get pandas dataframe from file
# cloumn names: img_url, house_type, price, address, ad_url, square, object_type, latitude, longitude
realEstateDataFrame = pd.read_csv('data/sell_test.csv')

with col1:
    # Show input for address
    address = st.text_input(
            "Please type address:",
            "Espoo")
    # Show select (st.selectbox) for type of property based on the list
    # generated by realEstateDataFrame object_type column
    # using 20 first rows of unique object_type 
    # corting by count of rows with this type
    # using descending order 
    # showing object_type
    object_type = st.selectbox(
            "Please select type of property:",
            realEstateDataFrame['object_type'].value_counts().head(20).index)
    
    # Show slider for number of rows to calculate average price
    # using 20 as default value
    # min value = 1 and max value = 100
    # step = 1 
    range_slider = st.slider(
            "Please select number of nearest points:",
            1, 100, 20, 1)

    # get geo coordinates and address by address
    lat, lon, adr = get_location_by_address(address)
    
    # get (range_slider) nearest points from dataframe and save it to new dataframe for st.map
    # filtered by object_type column
    df_for_map = get_nearest_points(realEstateDataFrame, lat, lon, range_slider, object_type)

    st.write('The address you entered is:', adr)
    # st.write('The latitude is:', lat)
    # st.write('The longitude is:', lon)

    # calculate average price for (range_slider) nearest points
    avg_price = df_for_map['price'].mean()
    # display average price
    st.write('Average price is:', avg_price)

with col2:
    # display map with markers based on the dataframe
    # st.map(df_for_map, zoom=11, latitude=lat, longitude=lon)
    # use folium library to display map with markers containing html content
    m = folium.Map(location=[lat, lon], zoom_start=11)
    # iterate over dataframe rows and add marker with html content
    folium.Marker(
            [lat, lon],
            popup='Your position',
            icon=folium.Icon(color='red', icon='info-sign')
        ).add_to(m)
    for index, row in df_for_map.iterrows():
        pp= folium.Popup(folium.Html('<h3>'
                        + row['address']
                        + '</h3><br/><img src="'
                        + row['img_url']
                        + '" width="200px" /><br/> Price: '
                        + str(row['price'])
                        + '<br/> House type: '
                        + row['house_type']
                        + '<br/><a href="'
                        + row['ad_url']
                        + '"target="_blank"> watch object </a>', script=True), max_width=250)
        folium.Marker(
            [row['latitude'], row['longitude']],
            popup=pp
        ).add_to(m)
    folium_static(m)
